steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/cv-generator', '.' ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/$PROJECT_ID/cv-generator' ]
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [ 'run', 'deploy', 'cv-generator', '--image', 'gcr.io/$PROJECT_ID/cv-generator', '--region', 'us-central1', '--platform', 'managed', '--allow-unauthenticated' ]
images:
  - 'gcr.io/$PROJECT_ID/cv-generator'
